### ISSUE TITLE
Builds are failing to push the image to image-registry 

### ISSUE THREAD

**Issue by harshad16** [operate-first/support#101]
**Describe the bug**
Observed that a build corresponding to a buildconfig is failing to push the image artifacts to the internal openshift image-registry.
The logs show error from go routines:
```
Copying blob sha256:8dd2e68bec49c531ef44d688795023b54fcca40fc25d3b1a2d2bb977a2282321
panic: d.nx != 0

goroutine 14001 [running]:
crypto/sha256.(*digest).checkSum(0xc000c34850, 0x0, 0x0, 0x0, 0x0)
	/opt/rh/go-toolset-1.13/root/usr/lib/go-toolset-1.13-golang/src/crypto/sha256/sha256.go:244 +0x1d9
crypto/sha256.(*digest).Sum(0xc000ea2000, 0x0, 0x0, 0x0, 0xc000c34978, 0xdf56b286, 0x8d2317cc2cc926b1)
	/opt/rh/go-toolset-1.13/root/usr/lib/go-toolset-1.13-golang/src/crypto/sha256/sha256.go:220 +0x76
github.com/opencontainers/go-digest.NewDigest(0x1bc37d2, 0x6, 0x1f1e4a0, 0xc000ea2000, 0x101, 0xc000c34eb8)
	/go/src/github.com/openshift/builder/vendor/github.com/opencontainers/go-digest/digest.go:40 +0x46
github.com/opencontainers/go-digest.(*digester).Digest(0xc00090e060, 0x1f16460, 0xc0000400f0)
	/go/src/github.com/openshift/builder/vendor/github.com/opencontainers/go-digest/digester.go:38 +0x49
github.com/containers/image/v5/docker.(*dockerImageDestination).PutBlob(0xc0006ee390, 0x1f16460, 0xc0000400f0, 0x1ecb880, 0xc0042b0118, 0x0, 0x0, 0xffffffffffffffff, 0x0, 0x0, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/v5/docker/docker_image_dest.go:172 +0x6bc
github.com/containers/image/v5/copy.(*copier).copyBlobFromStream(0xc00019e780, 0x1f16460, 0xc0000400f0, 0x1ecc100, 0xc0042b0108, 0xc000bb40f0, 0x47, 0xdea200, 0x0, 0x0, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/v5/copy/copy.go:1331 +0x56c
github.com/containers/image/v5/copy.(*imageCopier).copyLayerFromStream(0xc000e6aa40, 0x1f16460, 0xc0000400f0, 0x1ecc100, 0xc0042b0108, 0xc000bb40f0, 0x47, 0xdea200, 0x0, 0x0, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/v5/copy/copy.go:1131 +0x1c8
github.com/containers/image/v5/copy.(*imageCopier).copyLayer(0xc000e6aa40, 0x1f16460, 0xc0000400f0, 0xc000bb40f0, 0x47, 0xdea200, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/v5/copy/copy.go:1073 +0x373
github.com/containers/image/v5/copy.(*imageCopier).copyLayers.func1(0x7, 0xc000bb40f0, 0x47, 0xdea200, 0x0, 0x0, 0x0, 0x0, 0x1c1a4ef, 0x31, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/v5/copy/copy.go:828 +0x443
created by github.com/containers/image/v5/copy.(*imageCopier).copyLayers.func2
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/v5/copy/copy.go:860 +0x218
```

Related-to: https://github.com/thoth-station/amun-api/issues/611

**Comment by harshad16** [comment]
The update of the cluster zero has fixed this issue.
