### ISSUE TITLE
slack-first bot can't create issue

### ISSUE THREAD

**Issue by durandom** [operate-first/support#1152]
```
Slack event {"type":"modal","callback_id":"open_issue"}
[ERROR]  bolt-app UnknownError: [@octokit/auth-app] installationId option is required for installation authentication.
    at Object.asCodedError (/opt/app-root/src/node_modules/@slack/bolt/dist/errors.js:25:12)
    at App.handleError (/opt/app-root/src/node_modules/@slack/bolt/dist/App.js:527:43)
    at App.processEvent (/opt/app-root/src/node_modules/@slack/bolt/dist/App.js:520:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExpressReceiver.requestHandler (/opt/app-root/src/node_modules/@slack/bolt/dist/receivers/ExpressReceiver.js:152:13) {
  code: 'slack_bolt_unknown_error',
  original: Error: [@octokit/auth-app] installationId option is required for installation authentication.
      at getInstallationAuthentication (/opt/app-root/src/node_modules/@octokit/auth-app/dist-node/index.js:213:11)
      at hook (/opt/app-root/src/node_modules/@octokit/auth-app/dist-node/index.js:437:13)
      at /opt/app-root/src/node_modules/@octokit/plugin-request-log/dist-node/index.js:18:12
      at /opt/app-root/src/node_modules/before-after-hook/lib/register.js:25:15
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
}
(node:30) UnhandledPromiseRejectionWarning: Error: [@octokit/auth-app] installationId option is required for installation authentication.
    at Object.asCodedError (/opt/app-root/src/node_modules/@slack/bolt/dist/errors.js:25:12)
    at App.handleError (/opt/app-root/src/node_modules/@slack/bolt/dist/App.js:527:43)
    at App.processEvent (/opt/app-root/src/node_modules/@slack/bolt/dist/App.js:520:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExpressReceiver.requestHandler (/opt/app-root/src/node_modules/@slack/bolt/dist/receivers/ExpressReceiver.js:152:13)
(node:30) UnhandledPromiseRejectionWarning: Unhandled promise
```

cc @tumido 

I just added the bot to the #support channel

<img width="716" alt="image" src="https://user-images.githubusercontent.com/161888/203385175-70c1d529-b473-4ee3-8e0c-1be1764ec11d.png">

Wasnt he always there?

**Comment by tumido** [comment]
I think things may have changed on the github auth endpoint for apps... I need to take a closer look at the GitHub auth via Octokit and update it.

**Comment by tumido** [comment]
I'm also confused.. It was always there. And in other channels as well. No idea what happened. In my test slack workspace and test slack app the bot remains logged in and subscribed and is also capable of creating issues.. I'll look into this further, it's definitely weird.
