### ISSUE TITLE
OS-Climate CL1 cluster is unavailable

### ISSUE THREAD

**Issue by erikerlandson** [operate-first/support#605]
### Describe the Problem

The entire cluster appears to be unavailable: for example the console is not available.

### Steps to Reproduce

https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/   does not work

### Expected behaviour

should see console, etc

### Screenshots

![image](https://user-images.githubusercontent.com/259898/177346739-e73179cb-92c8-453e-aac7-88791256597e.png)

### Additional context

n/a

**Comment by HumairAK** [comment]
ocp authentication pods crashing: 

```
~ $ oc get pods -n openshift-authentication
NAME                               READY   STATUS             RESTARTS   AGE
oauth-openshift-5489c95548-q9qjr   1/1     Running            0          24h
oauth-openshift-5489c95548-svshh   1/1     Running            0          24h
oauth-openshift-7c4b8f8795-mvnfl   0/1     CrashLoopBackOff   1          16s
~ $ oc logs oauth-openshift-7c4b8f8795-mvnfl
Copying system trust bundle
I0705 15:59:15.341868       1 dynamic_serving_content.go:111] Loaded a new cert/key pair for "serving-cert::/var/config/system/secrets/v4-0-config-system-serving-cert/tls.crt::/var/config/system/secrets/v4-0-config-system-serving-cert/tls.key"
F0705 15:59:15.342141       1 cmd.go:49] failed to load SNI cert and key: tls: failed to find PEM block with type ending in "PRIVATE KEY" in key input after skipping PEM blocks of the following types: [CERTIFICATE CERTIFICATE]
goroutine 1 [running]:

```

likely something went wrong wtih recent cert update

**Comment by HumairAK** [comment]
Resolved: https://github.com/operate-first/operations/issues/485#issuecomment-1175318987
